name: build palworld-pterodactyl-proton
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - palworld-pterodactyl-proton/**
permissions:
  packages: write

jobs:
  push:
    name: "yolks:palworld-pterodactyl-proton_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./palworld-pterodactyl-proton
          file: ./palworld-pterodactyl-proton/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:palworld-pterodactyl-proton_${{ matrix.tag }}
            ${{ github.repository_owner == 'pelican-eggs' && format('ghcr.io/parkervcp/yolks:palworld-pterodactyl-proton_{0}', matrix.tag) || '' }}
